- hosts: isucon_server
  become: yes
  vars:
    tombouser: tombo
    isuconuser: isucon
  tasks:
    - name: update yum
      yum: name=* state=latest

    - name: import yum repositories
      yum: name={{ item }} state=installed
      with_items:
        - vim
        - htop
        - tmux
        - zsh
        - git

    - name: Set up tombo
      copy: >
        src=submodules/settings
        dest=/home/{{ isuconuser }}
        owner={{ isuconuser }}
        group={{ isuconuser }}
        mode=0755

    - name: Add user tombo
      user: name={{ tombouser }} shell=/bin/zsh group=wheel

    - name: Set up tombo
      copy: >
        src=submodules/dotfiles
        dest=/home/{{ tombouser }}
        owner={{ tombouser }}
        group=root
        mode=0755

    - name: set vimrc file
      file: >
        src=/home/{{ tombouser }}/dotfiles/vimrc
        dest=/home/{{ tombouser }}/.vimrc
        owner={{ tombouser }}
        group=root
        state=link
    - name: remove .zshrc
      file: path=/home/{{ tombouser }}/.zshrc state=absent

    - name: set zshrc file
      file: >
        src=/home/{{ tombouser }}/dotfiles/zshrc
        dest=/home/{{ tombouser }}/.zshrc
        owner={{ tombouser }}
        group=root
        state=link

    - name: set tmux file
      file: >
        src=/home/{{ tombouser }}/dotfiles/tmux.conf
        dest=/home/{{ tombouser }}/.tmux.conf
        owner={{ tombouser }}
        group=root
        state=link



    - name: (temporary) copy dotfiles to isucon user
      copy: >
        src=submodules/dotfiles
        dest=/home/{{ isuconuser }}
        owner={{ isuconuser }}
        group=root
        mode=0755

    - name: Change default shell to zsh
      user: name={{ isuconuser }} shell=/bin/zsh

    - name: (temporary) set zshrc file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/zshrc
        dest=/home/{{ isuconuser }}/.zshrc
        owner={{ isuconuser }}
        group={{ isuconuser }}
        state=link

    - name: (temporary) set vimrc file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/vimrc
        dest=/home/{{ isuconuser }}/.vimrc
        owner={{ isuconuser }}
        group={{ isuconuser }}
        state=link

    - name: (temporary) set tmux file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/tmux.conf
        dest=/home/{{ isuconuser }}/.tmux.conf
        owner={{ isuconuser }}
        group={{ isuconuser }}
        state=link



