- hosts: isucon_server
  become: yes
  vars:
    isuconuser: isucon
  tasks:

    - include: ubuntu.yml
      when: ansible_os_family == "Debian"

    - include: redhat.yml
      when: "ansible_os_family == 'RedHat'"

    - name: check isucon user exists ?
      stat: path=/home/isucon
      register: isucon_exist

    - name: Add group isucon
      group: name={{isuconuser}}
      when: not isucon_exist.stat.exists

    - name: Add user isucon for Ubuntu
      user: name={{ isuconuser }} shell=/bin/zsh group=sudo
      when: not isucon_exist.stat.exists and ansible_os_family == "Debian"

    - name: Add user isucon for RedHat
      user: name={{ isuconuser }} shell=/bin/zsh group=root
      when: not isucon_exist.stat.exists and ansible_os_family == "RedHat"

    - name: configure sudoers
      lineinfile:
        dest: /etc/sudoers
        backup: yes
        state: present
        regexp: '^isucon'
        insertafter: '^# %wheel'
        line: "isucon ALL=(ALL)  NOPASSWD: ALL"

    - name: mkdir /home/isucon/go
      file: path=/home/isucon/go state=directory owner={{ isuconuser }} group={{ isuconuser }} mode=0755

    - name: (temporary) copy dotfiles to isucon user
      copy: >
        src=dotfiles
        dest=/home/{{ isuconuser }}
        owner={{ isuconuser }}
        mode=0755

    - copy: src="pssh-key" dest="/home/{{isuconuser}}/.ssh/" owner=isucon group=isucon mode=0700

    - lineinfile: 
        dest: /home/{{isuconuser}}/.ssh/authorized_keys
        create: yes
        mode: 0755
        owner: "{{isuconuser}}"
        line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGKmh2FG2Pe4L9HVL8zF5Ij5XoPHKdEVAMopGi01MHmDav6jCkMZgN/suBxDYhs++h0+RdyG2gb59XNI1eoClf5ykHB7nz/xDPNMggUHHwZLUG+tbNv6gG+U1X3aQ+p3wB0ZUmyaQM7JIVlWu9NirgFCcJIU3adcz2p3b8JaS6sBgwGtiLq8kIcKxQHYvAJcp3OIfkm97sNodDccoGRRnQXnwNSb9YYZ5roVij4T052m08V/0BTvIDmam27Jse+rRjAEwMABtWAsjBlwP9NnDUKEiLrrtjwb9Teu8PCPzvpBSycpefsTtkcJfL82SUu5zNSaPhQuueKlmQTNZs1bwX k.osaka@sugahara-no-MacBook-Air-2.local"

    - name: Set up isucon set settings dir
      copy: >
        src=submodules/settings
        dest=/home/{{ isuconuser }}
        owner={{ isuconuser }}
        mode=0755

    - name: Set up isucon set nginx2els-kibana dir
      copy: >
        src=submodules/nginx2els-kibana
        dest=/home/{{ isuconuser }}
        owner={{ isuconuser }}
        mode=0755

    - name: Change default shell to zsh
      user: name={{ isuconuser }} shell=/bin/zsh

    - name: check .zshrc exists ?
      stat: path=/home/isucon/.zshrc
      register: zshrc_exist

    - name: Delete .zshrc if exist
      file: path=/home/isucon/.zshrc state=absent
      when: zshrc_exist.stat.exists

    - name: (temporary) set zshrc file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/zshrc
        dest=/home/{{ isuconuser }}/.zshrc
        owner={{ isuconuser }}
        state=link

    - name: check .zprofile exists ?
      stat: path=/home/isucon/.zprofile
      register: zprofile_exist

    - name: Delete .zprofile if exist
      file: path=/home/isucon/.zprofile state=absent
      when: zprofile_exist.stat.exists

    - name: (temporary) set zprofile file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/zprofile
        dest=/home/{{ isuconuser }}/.zprofile
        owner={{ isuconuser }}
        state=link

    - name: (temporary) set vimrc file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/vimrc
        dest=/home/{{ isuconuser }}/.vimrc
        owner={{ isuconuser }}
        state=link

    - name: (temporary) set tmux file
      file: >
        src=/home/{{ isuconuser }}/dotfiles/tmux.conf
        dest=/home/{{ isuconuser }}/.tmux.conf
        owner={{ isuconuser }}
        state=link

    - include: installGo.yml

    - script: ./submodules/settings/scripts/goget.sh


