- hosts: isucon_server
  remote_user: ec2-user
  become: yes
  vars:
    tombouser: tombo
    isuconuser: isucon
  tasks:

    - copy: src={{ item }} dest=/etc/nginx mode=0755
      with_files:
          - /statics/nginx.conf
          - /statics/mine.types


