- hosts: isucon_server
  become: yes
  vars:
    isuconuser: isucon
  tasks:
    - copy: src={{ item }} dest=/etc/nginx mode=0755
      with_items:
          -  statics/nginx.conf
          -  statics/mine.types

    - service: name=nginx state=restarted

